import {
  SiReact,
  SiVite,
  SiCloudflare,
  SiTypescript,
  SiHtml5,
  SiCss3,
  SiJavascript,
  SiPython,
  SiNodedotjs,
  SiMysql,
  SiExpress,
  SiPostgresql,
  SiPostman,
  SiCplusplus,
  SiLinux,
  SiUbuntu,
  SiGnubash,
  SiGodotengine,
  SiGithub,
  SiFigma,
  SiMui,
  SiYarn,
  SiPrettier,
  SiEslint,
  SiC,
  SiDocker,
  SiAxios,
} from 'react-icons/si';
import { 
  FaGitAlt,
  FaJava,
  FaFileCsv,
  FaItchIo,
} from 'react-icons/fa';
import { TbMarkdown, TbBrandNextjs } from 'react-icons/tb';
import { VscJson } from 'react-icons/vsc';
import '../styles/TechIcons.css';

// Tech icon mapping using react-icons
export const TECH_ICONS: Record<string, React.ComponentType<React.SVGProps<SVGSVGElement>>> = {
  react: SiReact,
  vitejs: SiVite,
  vite: SiVite,
  cloudflare: SiCloudflare,
  typescript: SiTypescript,
  html5: SiHtml5,
  css3: SiCss3,
  markdown: TbMarkdown,
  javascript: SiJavascript,
  js: SiJavascript,
  python: SiPython,
  nodejs: SiNodedotjs,
  mysql: SiMysql,
  expressjs: SiExpress,
  postgresql: SiPostgresql,
  postman: SiPostman,
  java: FaJava,
  'c': SiC,
  cpp: SiCplusplus,
  linux: SiLinux,
  ubuntu: SiUbuntu,
  bash: SiGnubash,
  godot: SiGodotengine,
  git: FaGitAlt,
  github: SiGithub,
  figma: SiFigma,
  nextjs: TbBrandNextjs,
  mui: SiMui,
  yarn: SiYarn,
  prettier: SiPrettier,
  eslint: SiEslint,
  csv: FaFileCsv,
  itchio: FaItchIo,
  json: VscJson,
  docker: SiDocker,
  axios: SiAxios,
};

// Display name mapping
const TECH_DISPLAY_NAMES: Record<string, string> = {
  react: 'React',
  vitejs: 'Vite',
  vite: 'Vite',
  cloudflare: 'Cloudflare',
  typescript: 'TypeScript',
  html5: 'HTML5',
  css3: 'CSS3',
  markdown: 'Markdown',
  javascript: 'JavaScript',
  js: 'JavaScript',
  python: 'Python',
  nodejs: 'Node.js',
  mysql: 'MySQL',
  expressjs: 'Express.js',
  postgresql: 'PostgreSQL',
  postman: 'Postman',
  java: 'Java',
  'c': 'C',
  cpp: 'C++',
  linux: 'Linux',
  ubuntu: 'Ubuntu',
  bash: 'Bash',
  godot: 'Godot',
  git: 'Git',
  github: 'GitHub',
  figma: 'Figma',
  nextjs: 'Next.js',
  mui: 'MUI',
  yarn: 'Yarn',
  prettier: 'Prettier',
  eslint: 'ESLint',
  csv: "CSV",
  itchio: 'itch.io',
  json: 'JSON',
  docker: 'Docker',
  axios: 'Axios',
};

export const getTechDisplayName = (tech: string): string => {
  return TECH_DISPLAY_NAMES[tech.toLowerCase()] || tech;
};
